// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: friends.sql

package sqlcgen

import (
	"context"
)

const countFriendship = `-- name: CountFriendship :one
SELECT COUNT(*) FROM friends WHERE user_id = ? AND friend_id = ?
`

type CountFriendshipParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) CountFriendship(ctx context.Context, arg CountFriendshipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFriendship, arg.UserID, arg.FriendID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFriend = `-- name: InsertFriend :exec
INSERT IGNORE INTO friends (user_id, friend_id) VALUES (?, ?)
`

type InsertFriendParams struct {
	UserID   int64
	FriendID int64
}

func (q *Queries) InsertFriend(ctx context.Context, arg InsertFriendParams) error {
	_, err := q.db.ExecContext(ctx, insertFriend, arg.UserID, arg.FriendID)
	return err
}

const listFriendIDs = `-- name: ListFriendIDs :many
SELECT friend_id FROM friends WHERE user_id = ?
`

func (q *Queries) ListFriendIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listFriendIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var friend_id int64
		if err := rows.Scan(&friend_id); err != nil {
			return nil, err
		}
		items = append(items, friend_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
