// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) FROM group_members WHERE group_id = ?
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembership = `-- name: CountMembership :one
SELECT COUNT(*) FROM group_members WHERE group_id = ? AND user_id = ?
`

type CountMembershipParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) CountMembership(ctx context.Context, arg CountMembershipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembership, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, avatar, owner_id, created_at FROM ` + "`" + `groups` + "`" + ` WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Avatar,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const insertGroup = `-- name: InsertGroup :execresult
INSERT INTO ` + "`" + `groups` + "`" + ` (name, avatar, owner_id) VALUES (?, ?, ?)
`

type InsertGroupParams struct {
	Name    string
	Avatar  string
	OwnerID int64
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertGroup, arg.Name, arg.Avatar, arg.OwnerID)
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT IGNORE INTO group_members (group_id, user_id, role) VALUES (?, ?, ?)
`

type InsertGroupMemberParams struct {
	GroupID int64
	UserID  int64
	Role    string
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const listGroupMemberIDs = `-- name: ListGroupMemberIDs :many
SELECT user_id FROM group_members WHERE group_id = ?
`

func (q *Queries) ListGroupMemberIDs(ctx context.Context, groupID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUser = `-- name: ListGroupsByUser :many
SELECT g.id, g.name, g.avatar, g.owner_id, g.created_at FROM ` + "`" + `groups` + "`" + ` g
JOIN group_members m ON g.id = m.group_id
WHERE m.user_id = ?
`

func (q *Queries) ListGroupsByUser(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGroupsByName = `-- name: SearchGroupsByName :many
SELECT id, name, avatar, owner_id, created_at FROM ` + "`" + `groups` + "`" + ` WHERE name LIKE CONCAT(?, '%') LIMIT ?
`

type SearchGroupsByNameParams struct {
	CONCAT interface{}
	Limit  int32
}

func (q *Queries) SearchGroupsByName(ctx context.Context, arg SearchGroupsByNameParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, searchGroupsByName, arg.CONCAT, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Avatar,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
