// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"time"
)

// 好友关系，双向各存一行
type Friend struct {
	UserID    int64
	FriendID  int64
	CreatedAt time.Time
}

type Group struct {
	ID        int64
	Name      string
	Avatar    string
	OwnerID   int64
	CreatedAt time.Time
}

type GroupMember struct {
	GroupID int64
	UserID  int64
	// owner | member
	Role     string
	JoinedAt time.Time
}

type User struct {
	ID           int64
	Identity     string
	Name         string
	PasswordHash string
	Email        string
	Phone        string
	Avatar       string
	Signature    string
	BirthDate    sql.NullTime
	IsAdmin      int8
	// 1正常 2封禁
	Status    int8
	CreatedAt time.Time
	UpdatedAt time.Time
}
