// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const getByEmail = `-- name: GetByEmail :one
SELECT id, identity, name, password_hash, email, phone, avatar, signature, birth_date, is_admin, status, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.Name,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Signature,
		&i.BirthDate,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByIdentity = `-- name: GetByIdentity :one
SELECT id, identity, name, password_hash, email, phone, avatar, signature, birth_date, is_admin, status, created_at, updated_at FROM users WHERE identity = ?
`

func (q *Queries) GetByIdentity(ctx context.Context, identity string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByIdentity, identity)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.Name,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Signature,
		&i.BirthDate,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, identity, name, password_hash, email, phone, avatar, signature, birth_date, is_admin, status, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.Name,
		&i.PasswordHash,
		&i.Email,
		&i.Phone,
		&i.Avatar,
		&i.Signature,
		&i.BirthDate,
		&i.IsAdmin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT id, identity, name, password_hash, email, phone, avatar, signature, birth_date, is_admin, status, created_at, updated_at FROM users WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetUsersByIDs(ctx context.Context, ids []int64) ([]User, error) {
	query := getUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.Name,
			&i.PasswordHash,
			&i.Email,
			&i.Phone,
			&i.Avatar,
			&i.Signature,
			&i.BirthDate,
			&i.IsAdmin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (identity, name, password_hash, email) VALUES (?, ?, ?, ?)
`

type InsertUserParams struct {
	Identity     string
	Name         string
	PasswordHash string
	Email        string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser,
		arg.Identity,
		arg.Name,
		arg.PasswordHash,
		arg.Email,
	)
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, identity, name, password_hash, email, phone, avatar, signature, birth_date, is_admin, status, created_at, updated_at FROM users
WHERE identity LIKE CONCAT(?, '%') OR name LIKE CONCAT(?, '%') OR email LIKE CONCAT(?, '%')
LIMIT ?
`

type SearchUsersParams struct {
	CONCAT   interface{}
	CONCAT_2 interface{}
	CONCAT_3 interface{}
	Limit    int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.Name,
			&i.PasswordHash,
			&i.Email,
			&i.Phone,
			&i.Avatar,
			&i.Signature,
			&i.BirthDate,
			&i.IsAdmin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
  name       = COALESCE(?, name),
  phone      = COALESCE(?, phone),
  email      = COALESCE(?, email),
  avatar     = COALESCE(?, avatar),
  signature  = COALESCE(?, signature),
  birth_date = COALESCE(?, birth_date)
WHERE id = ?
`

type UpdateUserParams struct {
	Name      sql.NullString
	Phone     sql.NullString
	Email     sql.NullString
	Avatar    sql.NullString
	Signature sql.NullString
	BirthDate sql.NullTime
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Avatar,
		arg.Signature,
		arg.BirthDate,
		arg.ID,
	)
	return err
}
